docs/python/environment-venv.rst.include
I have swapped the venv-vscode and venv-terminal. The layout has now changes so venv-vscode is the first environment guide.
=> Swap venv-Vscode and venv-terminal

Dockerfile
Added `sphinx>=7.2.5` to Dockerfile, to fix missing Jinja2 templating.
Also, seperate `COPY ./requirements.txt /app-src/requirements.txt`. This enables near-parity in performance with pure host `make all`.
=> deploy: Optimized and fixed podman.

tools/scuffed-scraper/.gitignore, tools/scuffed-scraper/LICENSE, tools/scuffed-scraper/README.md, tools/scuffed-scraper/main.py, tools/scuffed-scraper/requirements.txt
Should all work according to the README.
Also see README for instructions on how to use the TOML output.
=> Added scuffed scraper tool.

docs/_static/css/custom_styles.css, docs/conf.py
-Buttons added to the right
-Header fixed when scrolling down
=> Add buttons

docs/_static/css/custom_styles.css
Now the right side bar is static, like the header
=> Right side bar static

docs/_static/css/.styleintrc.json, docs/_static/css/bannerStyles.css, docs/_static/css/colors.css, docs/_static/css/custom_styles.css, docs/_static/css/fontawesome5.css, docs/_static/css/fontawesome6.css, docs/_static/css/popupStyles.css, docs/_static/css/questionairStyles.css
-Now all .css files are styled according to stylelint-config-standard package.
-I've also added a .styleintrc.json that can be used to further optimize the .css files as wanted.
Note: I decided to go with this stylelint package because:
1- It seems to be periodically maintained.
2- It does not produce dramatic changes in the .css files.
=> Updated code according to stylelint-standard

docs/install/macos/automated.rst, docs/install/macos/homebrew.rst, docs/install/macos/manual.rst
=> Typos installation guides fixed

docs/learn-more/terminal.rst, docs/uninstall/index.rst, docs/uninstall/uninstall-conda.rst, docs/uninstall/uninstall-python.rst, docs/uninstall/uninstall-vscode.rst
Updated Terminal section by adding all the points form Kasper's temrinal video. For all the command sin the video, there is no difference between Windows and Mac, so i have implemented no distinction between these. 
Also cleaned up the uninstall software section, by fixing some typos and spelling errors. Changed link in index file to go to the new "packages and environments page" instead of the old "environments" page. There was a toctree in the index file, that was hidden, but I made it visible for more clarity.
=> Charlie-Updating-temrinal-section

docs/conf.py, docs/install/macos/automated.rst, docs/install/macos/homebrew.rst, docs/install/macos/manual.rst, docs/install/windows/automated.rst, docs/install/windows/manual.rst, docs/learn-more/packages-and-environments.rst
Introduced a new way of communicating the installation guides.
Note that we would like to use this style throughout the website to be consistent and clear
=> Manual mac installation changed

docs/install/macos/automated.rst, docs/install/macos/homebrew.rst, docs/install/macos/manual.rst, docs/install/macos/verify.rst, docs/install/windows/automated.rst, docs/install/windows/manual.rst, docs/install/windows/verify.rst
Insert videodropdown in all installation guides and added link for two of the guides. Also fixed images in the verify files.
=> Insert videodropdown in all installation guides

docs/videotutorials/index.rst
-Some videos are still missing.
-Links to Learn More section should be added to some videos
=> Video tutorials added with introduction message to videos

docs/uninstall/uninstall-conda.rst
I have changed the uninstall of conda to take into consideration different kind installations for MacOS including install of conda with and without homebrew
=> Uninstall changed

docs/videotutorials/index.rst
Added videos to the video tutorials page
=> Charlie-adding-videos-to-video-tutorials-section-16-august

docs/videotutorials/index.rst
Fixed some typos in headers and added the automated installation video for macos
=> Charlie-16-august-adding-last-video-for-automated-mac-install

docs/install/macos/homebrew.rst, docs/install/macos/manual.rst, docs/install/macos/verify.rst, docs/install/windows/manual.rst, docs/install/windows/verify.rst
=> added scipy and statsmodels

.github/workflows/create-doc.yaml, docs/_rst_includes/course-default-pg-installation.rst, docs/os/gifs/create.sh
Currently the cache is now fully functional.
I.e. we have to download and install everything, even if not necessary this may be fixed later.
=> fixing gifs when new are added

docs/_static/css/bannerStyles.css, docs/html/main_banner.html
I still need to convert the whole button to be reactive, I'll have it done during this week
=> Changes to the main button, now is DTU Blue and only 1 button instead of 2

docs/_static/css/custom_styles.css, docs/_static/js/custom.js
Here is the zoom-in feature we talked about at the meeting. It should work for any image on the site
=> Zoom-in image display feature implemented

docs/html/main_banner.html
- Note that this can be readapted in many different ways. Currently, the whole button and 'Click here to install Python!' are responsive, but the 'Are you a 1st year student?' could also be responsive if wanted.
=> Made the whole button responsive

docs/_static/css/bannerStyles.css, docs/_static/css/colors.css, docs/_static/css/custom_styles.css, docs/_static/css/fontawesome5.css, docs/_static/css/fontawesome6.css, docs/_static/css/popupStyles.css, docs/_static/css/questionairStyles.css
This pull formats all the CSS files with the default CSS-formatter in VS-code. This ensures consistent code style throughout the stylessheets in the project.
=> Consistent CSS formatting

docs/_static/css/custom_styles.css
This pull fixes responsiveness problems on all pages.
=> Better responsiveness

docs/_static/css/colors.css, docs/_static/css/custom_styles.css, docs/html/hero.html, docs/index.rst
This pull implements a Hero for the homepage. 
This Hero is an adaptation from [this](https://getbootstrap.com/docs/5.0/examples/heroes/).
=> Hero for the homepage

docs/commonproblems/index.rst, docs/index.rst, docs/videos/index.rst
Added dropwons to the already existing video tutorials page, and added the common errors page with the same dropdown-style as video tutorials. 
NOTE: THERE IS NO CAROUSEL FUCKERY ON THIS ONE!
=> Adding-dropdowns-without-carousels

docs/index.rst
Removes the extra-info for the exam opening.
Merge tonight
=> removed extra open on 6th of December

docs/index.rst, docs/ps_configuration.toml, docs/timetable/timetables.rst
Removed exam open note and added note that we are first open in the Spring semester.
Merge this on the 19th of December (in the evening).
=> prepared for next semester

docs/_static/js/piwik.js, docs/conf.py
Currently, the privacy question is not looking great. We should hear DTU about how they got their cookie looking
=> added piwik extension

docs/_static/css/custom_styles.css
This pull fixes the style issue with the "see tutorials" button in the hero. The button color is changed to match to adhere to the red color theme.
=> Link button color change

docs/_static/css/custom_styles.css
This pull adds custom css to align text inputs to the DTU color scheme.
=> Added custom styles for text inputs

docs/conf.py, docs/faqs/faq-windows.rst.include, docs/install/python.rst, docs/ps_modules/mailto_role.py
The mailto was broken.
This fixes the remaining issues
=> fixed #179

docs/install/macos/verify.rst, docs/install/windows/verify.rst
Updated verification videos for Mac and windows with a note commenting on python versions
=> updated verification videos
